image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  CI_REGISTRY_IMAGE: $CI_REGISTRY/tu-usuario/cms-frontend

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_frontend:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
